name: backend
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  # o shelf tem tudo disponivel para criar o servidor
  shelf: ^1.4.1
  # shelf router disponibiliza uma serie de recursos para trabalhar com nossos metodos http
  shelf_router: ^1.1.4 

  #faz 3 coisas, vai grar no JWT, faz a assinatura, faz a verificacao se o jwt é valido ou não
  dart_jsonwebtoken: ^2.7.1

  #dependencia do msql para o banco de dados
  mysql1: ^0.20.0

  #para gerar o hash da senha
  password_dart: ^2.0.1
